### ISSUE TITLE
County Screen - VoiceOver Changes Focus from Seasonal Toggle to Application Heading

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#12]
When I tested with VoiceOver on the iPad, I noticed that VoiceOver first focused on the "Seasonally Adjusted" toggle switch and it went to the heading of the application in the top left of the screen. Doing so makes it confusing and difficult to get to the "State" content. I'm wondering why the application on the iPad has the list of cities, states, or counties on the left-hand side of the application? I would expect that to be gone when on another screen beside the home/search screen as it is on the iPhone. Even when I go to the "City" screen, it does the same thing.

See attached screenshots.

Screenshot of VoiceOver focus on Seasonal toggle

![bls local data - ipad - state screen focus on seasonally adjusted toggle](https://user-images.githubusercontent.com/10423487/56240981-b3bbc680-6062-11e9-89a9-d4d6bd08c054.png)

Screenshot of VoiceOver Focus now on Application heading on left-hand side

![bls local data - ipad - state screen focus on application heading](https://user-images.githubusercontent.com/10423487/56240990-ba4a3e00-6062-11e9-9545-65fdc9f48464.png)

**Comment by chawlani** [comment]
Made changes so that detail view rakes whole screen to avoid the issue of focus

**Comment by jfc3-dol** [comment]
When I choose a county on the iPad and use the "Local Labor Market Data" button the screen to go back, the application focuses to the split-screen which shows the search list options and focuses on the "Switch to full-screen mode" button. 

I thought you were going to have the screens full the screen instead of having the search options on them when using a wider screen like for our iPad? If so it should work on al the screens.

Please see the attached screenshots.

County screen highlighting "Local Labor Market Data" button

![bls local data - ipad - county screen highlighting local labor market data button](https://user-images.githubusercontent.com/10423487/56592509-d1d07c00-65b8-11e9-9139-35a2b9993a53.png)

County screen showing search list options and highlighting "Switch to full-screen mode" button

![bls local data - ipad - county screen showing search list options and higlighting switch to full-screen mode button](https://user-images.githubusercontent.com/10423487/56592518-d72dc680-65b8-11e9-8213-2b7afd02501d.png)

**Comment by chawlani** [comment]
I'm using SplitScreen view to use which is available on iPads, which uses the extra space to display master and detail screens. the button gives user the ability to view screens inn split view as other Apple apps ex - Mail, Safari. The button provides a way to switch between the full screen mode and split mode and users are used to this functionality on iPAd.

**Comment by jfc3-dol** [comment]
I was expecting to stay in full-screen mode since the other screens were in full-screen mode and not go to split-screen for one of them.

My biggest concern is how does a user get to the search options on the left side using VoiceOver without having to back tab through either the list of almost 400 cities, 50 states, etc.? Maybe we need to think about this a bit.

**Comment by jfc3-dol** [comment]
When using VoiceOver, the focus goes to the top of the search overlay and then when it starts reading again it works through the next items works.

So going to close this issue
