### ISSUE TITLE
Accessibility - City  Screen - Reading Order Issues for TABLE Headings

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#13]
I also noticed that when reading through the content of a sub-page/group I noticed that the reading order of the items above the TABLE on information is reading incorrectly. A VoiceOver reads the city and then the month and year followed by "Industry", "Employment Level", "Code" along with the instruction, then "(in thousands)", etc. I would expect VoiceOver to read "Industry code" and instructions followed and then "Employment Level (in thousands)".

See attached screenshots with current reading order which use numbers and the letters are for expected reading order.

Screenshot of reading order the the top of the TABLE section of the screen

![bls local data - ipad - city screen details reading order](https://user-images.githubusercontent.com/10423487/56241116-0b5a3200-6063-11e9-8b54-9bfb4dcb8111.png)

**Comment by chawlani** [comment]
Updated Headings views reading order as recommended

**Comment by jfc3-dol** [comment]
VoiceOver is reading everything in the correct order now except for the "Industry Code" section which is being done as two separate words instead of one group of words.

**Comment by chawlani** [comment]
Its reading them as different because one is static text and other is button which is used to sort

**Comment by jfc3-dol** [comment]
I would expect them to be read as one item otherwise VoiceOver reads "XYZ" then "Code button" which doesn't tell the user what the button is about.

**Comment by jfc3-dol** [comment]
VoiceOver is now reading the items in the order expected but not highlighting all the words that are being read which I'm not as concerned about being an issue.

Thanks, for fixing the issues, so I am going to close this issue now.
