### ISSUE TITLE
Accessibility - City Screen - Confusing Text between Heading and Button

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#14]
Why when reading the "Industry Employment" does VoiceOver read "Industry Employment heading" for the text but then reads "Industry Hierarchy button heading tap to view Industry Hierarchy". Is there a reason the first item is "Industry Employment" and the second uses the term "Industry Hierarchy"? 

I would expect them both the heading and the button to start with "Industry Employment" and the button to have additional information about the button but first say "Industry Employment more details" or "More details about Industry Employment". Both followed by the word button and any instructions about how to activate it.

**Comment by chawlani** [comment]
Had changed the button to say "detail" but will change it to "Industry Employment more details" and for Occupations button to say "Occupations more details"

**Comment by jfc3-dol** [comment]
Thanks, I think using whatever the heading text is along with the words "more details" for all the buttons makes sense.

**Comment by jfc3-dol** [comment]
I like that the buttons to the other screens with more details now have the text "more details" after the name and code. Is the word "heading" being added at the end because the non-button text is a heading or the whole row is wrapped in a heading?

**Comment by chawlani** [comment]
the whole title row  is a header hence button is being read as heading also. I have tried to remove "heading" but iOS is adding it.

**Comment by jfc3-dol** [comment]
It the issue with reading the word "heading" after the button because it's on the same row or the whole row is wrapped in code denoting it's a heading? I'm not as familiar with iOS coding as I am with HTML/web pages.

**Comment by chawlani** [comment]
I had informed you about this issues if we keep the title and button read separately on 04/15 and 4/16 and that why I had suggested to keep them together and read as heading and button. Let me know if I should change it back to that.

**Comment by jfc3-dol** [comment]
Let me think about it.

**Comment by jfc3-dol** [comment]
Each piece of text should be its own link to a person can skip back a few levels instead of only being able to go back one level at a time. To me, these remind me of bread crumbs which you can click or tap on any of the links/items listed.

**Comment by jfc3-dol** [comment]
I can tap on the individual links when VoiceOver is off and it takes me to the correct screen but when VoiceOver is on it only goes back one screen because it's acting as one link.

**Comment by jfc3-dol** [comment]
Sorry, about putting the wrong notes in this issue.

I'm going to close this issue now even though VoiceOver reads "heading" at the end of the button because it's part of a heading row.
