### ISSUE TITLE
Accessibility - City Screen - VoiceOver Reads Same Text for Second Button as the First Button

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#15]
When VoiceOver reads the second new section on the screen related to "Occupational Employment and Wages" it reads the button as "Industry Hierarchy button"? It's even more confusing than the previous issue.

**Comment by chawlani** [comment]
Changed the button to read "details"

**Comment by chawlani** [comment]
For all right arrows, voiceover will read the "<title> more details"

**Comment by jfc3-dol** [comment]
Thanks, for now making the button be the TITLE and the text "more details".

Of the random screens I tested, I found this to be working as now updated. So I'm going to close the issue.
