### ISSUE TITLE
Accessibility - City Screen (iPad)  - Different Display Option than the iPhone

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#16]
When I tap on the "Industry Hierarchy button" on our iPad Air 2 it displays the new content in the righthand side of the screen and focuses on the city of Akron, OH text from the list instead of the "Industry - Sectors" section/text so it will then read the newly displayed content. When I attempted to have, VoiceOver read it start at Akron, OH in the list of locations and continued to read the rest below them. I stopped it after a few cities and tapped on the top of the right-hand section because I could, but for someone else using VoiceOver, they would likely have to listen to the rest of the list.

**Comment by chawlani** [comment]
Changed the detail screen to take full screen to avoid the problem

**Comment by jfc3-dol** [comment]
When I use the Button to go back to the main city screen it now shows the city content on half the screen and the search options on the other. From your comment above I was expecting the application to be in full screen mode on the iPad all the time and not some of the time.

Please see the attached screenshots.

County screen highlighting "Local Labor Market Data" (back) button

![bls local data - ipad - county screen highlighting local labor market data button](https://user-images.githubusercontent.com/10423487/56610221-f0486e80-65dc-11e9-9d4c-157274cd9422.png)

County screen showing search list options and highlighting the "Switch to Full-screen Mode" button

![bls local data - ipad - county screen showing search list options and higlighting switch to full-screen mode button](https://user-images.githubusercontent.com/10423487/56610211-ede61480-65dc-11e9-8aab-26d1954727b7.png)

**Comment by chawlani** [comment]
To display 2 screens in split view is a feature of iPad so use the space. I don't want to take away the feature. I had changed it earlier since the focus was returning to left screen. I'll change it back to use split screen and try to work with focus.

**Comment by jfc3-dol** [comment]
Going back to one of the other issues I mentioned it would make it more difficult for VoiceOver users to get to the search option or change from city to state or county by having the split screen.

**Comment by jfc3-dol** [comment]
When using VoiceOver, the focus goes to the top of the search overlay and then when it starts reading again it works through the next items works.

So going to close this issue
