### ISSUE TITLE
Accessibility - City (More Details) Screen - VoiceOver Not Reading Right Pointing Arrows Correctly

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#17]
I noticed on the "Industry - Sectors" screen there were right-pointing arrows that VoiceOver never announced which after turning off VoiceOver I could tap to see more details.

With the latest update Tuesday, evening some of them are being read as "Right chevron" which I'm assuming is the file name. Think the application should read the name for the row along with the more detail information as part of the button.

We should look into the best way to do this for all the different screens that then point to another screen with more details.

**Comment by chawlani** [comment]
Will do

**Comment by jfc3-dol** [comment]
All the screens I read with VoiceOver read the buttons as the TITLE of the row and "more details" instead of "Right chevron". So I'm going to close this issue.
