### ISSUE TITLE
Accessibility - City - "Industry Sector" Screen Display Issue

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#19]
While testing with VoiceOver on the "Industry Sector" screen for Akron, OH, for the "Government 90000000) sector I noticed the last row has the industry name and code followed by "N/A" once and an arrow for more details. I would have assumed all the different field locations would have "N/A" and not the "Level" one column only.

Also, if there is no data for a given industry why is there a link to more details screen that doesn't list much if any data, the industry name, and code is the following:

Total State and Local Government (90940000)

Please see attached screenshots.

Highlighted "Industry Sector" city row with only one N/A

![bls local data - ipad - city screen - highlighting industry sector city row with only one na](https://user-images.githubusercontent.com/10423487/56603249-5dec9e80-65cd-11e9-89fe-a624a666b406.png)

Highlighted "Industry Sector" screen with two items with one N/A each

![bls local data - ipad - city screen - highlighting industry sector and two items with one na](https://user-images.githubusercontent.com/10423487/56603254-60e78f00-65cd-11e9-8ede-14321e91488a.png)

**Comment by chawlani** [comment]
If the Level is N/A then there can't be 1 month change and 12 month Change hence these fields are empty. and There are cases where the parent industry data is not available but children industries may have data. BLS stakeholders are aware of such cases.

**Comment by jfc3-dol** [comment]
My thinking is that if the "Level" is N/A, then the others could have something or should also have N/A so the user isn't wondering about the other fields are empty.

Now that you explained that a parent could be empty but the children can have data then we need to link to see that detail. I was assuming that if a parent had no data, the child would, or there wouldn't be any children.

**Comment by jfc3-dol** [comment]
Having the "N/A" at least once under each column is better than having nothing there for two columns.

I'm going to close this issue.
