### ISSUE TITLE
Functional - Table Row Display Moves when Using VoiceOver

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#20]
While testing with VoiceOver, I noticed that the white space between the rows in the TABLE widens as you read through the TABLE with VoiceOver.

Some people use a screen reader that is not blind to read along because of poor vision, or English is a second language or cognitive issues, so they know where they are at when reading.

Please see attached screenshots.

No gap between table heading and first row.

![bls - ios - detail screen with no gap between table heading and first row](https://user-images.githubusercontent.com/10423487/56985098-95bb8f00-6b55-11e9-8d17-ab0f43cc99d2.png)

Wider gap between table heading and first row.

![bls - ios - detail screen with wider gap between table heading and first row](https://user-images.githubusercontent.com/10423487/56985169-b5eb4e00-6b55-11e9-96f9-5981675816f7.png)

**Comment by chawlani** [comment]
This is iOS behavior and have been unable to change it. I checked other Apple apps like Mail and Contacts and they have similar behavior.

**Comment by jfc3-dol** [comment]
Okay, wasn't sure and had not seen it in any of my other testing previously of other application. The only ones that will notice it are visual VoceOver users or maybe someone using an attached keyboard. 

Going to close the issue if you are not able to fix this one.
