### ISSUE TITLE
Accessibility - VoiceOver Not Telling User Sort Order on Detail Screen 

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-IOS#21]
While testing with VoiceOver, we noticed that it's not telling the user the order the detail screen table content is sorted in.

When a user goes to the table section and then reads the table headings, VoiceOver reads the table heading and tells them it can be sorted. If the user double taps the item to sort it, they are not notified in what order it is now sorted in. VoiceOver does tell them the column that was sorted but not the order the column/table is now sorted in.

Please see screenshot to show which table items I'm talking about.

![bls - ios - detail screen voiceover not announcing table sort order](https://user-images.githubusercontent.com/10423487/57022656-cc4ce480-6bfd-11e9-8a94-cd9f540f797d.png)

**Comment by chawlani** [comment]
When a button is clicked, the selection stays on the button, so Voiceover reads the button label again by default.
Hence adding Announcement String didn't work. I was however able to add a accessibility value to the button with sort order.
Ex - After Clicking on Level, Voice over announces Level by default and with added Value, it will announce it as "Level ascending". Please let me know if that would work.

**Comment by jfc3-dol** [comment]
Sound like a plan.

I know with the BLS Local Data application for their toggle switch it tells the users what information is showing depending on the new state. But I'm guessing that is not an option when it's in a TABLE/view.

Will give it a look once I get the new build.

**Comment by jfc3-dol** [comment]
I like when I tap on one of the column headings it tells the user the order the TABLE is now in.

My only question is, are the items sorted by the number in the first column instead of the words? If so everything is okay, but I was assuming they would be in word order under the TABLE heading.

Please see the screenshot of items sorted in ascending order by number.

![bls - ios - detail screen voiceover announcing table sort order but industry code is by numbers not text](https://user-images.githubusercontent.com/10423487/57245228-51723800-7008-11e9-9682-31ad11dbd551.png)

**Comment by chawlani** [comment]
Clicking on first Column (Industry Code or Occupation Code) sorts the items one Code Value (number value.

**Comment by jfc3-dol** [comment]
Thanks, I wanted to make sure the sort was happening correctly since I was expecting it to be sorted by names and not numbers.

Closing this issue because the sort is working as expected.
